spring:
    application:
        name: product-service
    data:
        mongodb:
            database: productdb
            # host:
            # port: 27017
            # username: 
            # password: 

server:
  port: 8091